### ISSUE TITLE
updw +LPF: mat1 and mat2 shapes cannot be multiplied (24588x1024 and 4800x1)

### ISSUE THREAD

**Issue by alice-cool** [jokieleung/LPF-VQA#1]
Dear scholar:

When I run python -m bootstrap.run -o rubi/options/vqacp2/lpf_updn.yaml
The code throw exceptions as follows:
LPF-VQA/rubi/models/networks/updn.py", line 90, in logits     logits = self.linear(joint_repr)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (24588x1024 and 4800x1)

我直接将q_dim 改为1024 即可跑通
class NewAttention(nn.Module):
    def __init__(self, v_dim, q_dim, num_hid, dropout=0.2):
        super(NewAttention, self).__init__()

        self.v_proj = FCNet([v_dim, num_hid])
        self.q_proj = FCNet([q_dim, num_hid])
        self.dropout = nn.Dropout(dropout )
        #self.linear = weight_norm(nn.Linear(q_dim, 1), dim=None)
        self.linear = weight_norm(nn.Linear(1024, 1), dim=None)

**Comment by alice-cool** [comment]
在python3.9 会报错
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [683, 2048]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
将inplace 置为false 就可运行
class SimpleClassifier(nn.Module):
    def __init__(self, in_dim, hid_dim, out_dim, dropout):
        super(SimpleClassifier, self).__init__()
        layers = [
            weight_norm(nn.Linear(in_dim, hid_dim), dim=None),
            nn.ReLU(),
            #nn.Dropout(dropout, inplace=True),
            nn.Dropout(dropout, inplace=False),
            weight_norm(nn.Linear(hid_dim, out_dim), dim=None)
        ]
        self.main = nn.Sequential(*layers)

    def forward(self, x):
        logits = self.main(x)
        return logits

**Comment by alice-cool** [comment]
Dear scholar, could I think the Up + Focal loss  only  point your same loss function when the r is set 1.

![1660276207390](https://user-images.githubusercontent.com/16870890/184281784-b60d36fd-4b9f-4d96-a776-949318b08b32.jpg)

**Comment by jokieleung** [comment]
> 

Hi Alice, as I mentioned in the paper, UpDn+Focal varient is based on the modified alpha_i, which is computed by the outputs from the VQA model itself.
